- name: create Jenkins container
  docker_container:
    name: jenkins
    image: jenkins/jenkins:lts
    restart_policy: always
    state: started
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - name: env
