- name: create container with Sonatype Nexus
  docker_container:
    name: nexus
    image: sonatype/nexus3
    restart_policy: always
    state: started
    volumes:
      - nexus-data:/nexus-data\
    hostname: nexus
