- name: create database for sonarqube
  docker_container:
    name: sonar-postgres
    image: postgres:9.6
    restart_policy: always
    volumes:
      - sonar-postgres-data:/var/lib/postgresql/data
    networks:
      - name: env
    env:
      POSTGRES_USER: sonar
      POSTGRES_DB: sonar
      POSTGRES_PASSWORD: "{{ SONAR_POSTGRES_PASSWORD }}"

- name: create sonarqube container
  docker_container:
    name: sonarqube
    image: sonarqube
    restart_policy: always
    state: started
    networks:
      - name: env
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    env:
      sonar.jdbc.username: sonar
      sonar.jdbc.password: "{{ SONAR_POSTGRES_PASSWORD }}"
      sonar.jdbc.url: jdbc:postgresql://sonar-postgres/sonar
