- import_tasks: prepare.yml

- name: create Nginx reverse proxy
  docker_container:
    name: nginx-proxy
    image: nginx
    restart_policy: always
    state: started
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d/
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks_cli_compatible: yes
    networks:
      - name: env

- name: reload Nginx
  shell: docker exec nginx-proxy nginx -s reload
