- name: configure /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ ANSIBLE_HOST }} node.{{ DOMAIN }} node"

- name: configure localhost
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1  localhost.localdomain localhost'

- name: configure /etc/hostname
  hostname:
    name: node.{{ DOMAIN }}
