- name: install bind9
  apt:
    name: bind9
    update_cache: yes
- name: configure apparmor
  lineinfile:
    line: '/var/lib/named/** rwm,'
    regexp: '^/var/lib/named'
    path: /etc/apparmor.d/local/usr.sbin.named
  notify: apparmor reload
