- import_tasks: install.yml
- import_tasks: hosts.yml

- name: configure bind9 options
  lineinfile:
    path: /etc/default/bind9
    regexp: '^OPTIONS='
    line: OPTIONS='-u bind -t /var/lib/named'

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ['/var/lib/named/etc', '/var/lib/named/etc/bind',  '/var/lib/named/var/cache/bind', '/var/lib/named/var/run', '/var/lib/named/dev']

- name: move bind9 configuration files
  copy:
    remote_src: yes
    src: /etc/bind
    dest: /var/lib/named/etc

- name: remove old configuration files
  file:
    path: /etc/bind
    state: absent

- name: create symlink in /etc/bind
  file:
    src: /var/lib/named/etc/bind
    dest: /etc/bind
    state: link

- import_tasks: create-devices.yml

- name: set files and directories permissions
  file:
    path: "{{ item }}"
    mode: 0666
  with_items:
    - ["/var/lib/named/dev/null", "/var/lib/named/dev/random"]

- name: change owner to bind
  file:
    path: "{{ item }}"
    owner: bind
    group: bind
    recurse: yes
  with_items:
    - ['/var/lib/named/var/', '/var/lib/named/etc/bind']

- name: create named.conf.options
  template:
    src: templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: bind
    group: bind
    mode: 0644

- name: create named.conf.local
  template:
    src: templates/named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: bind
    group: bind
    mode: 0644

- name: copy DNS configuration
  template:
    src: templates/domain.zone.j2
    dest: /etc/bind/{{ DOMAIN }}
    owner: bind
    group: bind
    mode: 0644
  notify: restart bind9
