- import_tasks: install.yml
- import_tasks: hosts.yml

- name: configure bind9 options
  lineinfile:
    path: /etc/default/bind9
    regexp: '^OPTIONS='
    line: OPTIONS='-u bind -t /var/lib/named'

- import_tasks: directories-configuration.yml
- import_tasks: create-devices.yml

- name: create named.conf.options
  template:
    src: templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: bind
    group: bind
    mode: 0644

- name: create named.conf.local
  template:
    src: templates/named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: bind
    group: bind
    mode: 0644

- name: copy DNS configuration
  template:
    src: templates/domain.zone.j2
    dest: /etc/bind/{{ DOMAIN }}
    owner: root
    group: root
    mode: 0644
  notify: restart bind9
