- hosts: all
  become: true
  roles:
    - {role: docker, tags: docker}
    - {role: nexus, tags: nexus}
    - {role: jenkins, tags: jenkins}
    - {role: graylog, tags: graylog}
    - {role: gitlab, tags: gitlab}
    - {role: nginx, tags: nginx}
    - {role: dns, tags: dns}
