- name: create GitLab container
  docker_container:
    name: gitlab
    image: gitlab/gitlab-ce
    restart_policy: always
    state: started
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
    ports:
      - '2222:22'
    hostname: gitlab
    networks:
      - name: env
    env:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '{{ GITLAB_EXTERNAL_URL }}'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
